const analytics = [
  {
    storeId: 1,
    userId: 1,
    itemId: null,
    isStore: true,
    itemName: null,
    weekViews: 100,
    dayViews: 10,
    lifeTimeViews: 1000,
    totalStars: 4,
    totalReviewers: 10,
    totlaShares: 10,
    totalComments: 19,
    totalRevenueUSD: 1000,
    totalRevenueIQD: 100000,
    totlaItemSales: 10,
  },
  {
    storeId: 1,
    userId: 1,
    itemId: 1,
    isStore: false,
    itemName: 'itemName',
    weekViews: 100,
    dayViews: 10,
    lifeTimeViews: 1000,
    totalStars: 4,
    totalReviewers: 10,
    totlaShares: 10,
    totalComments: 19,
    totalRevenueUSD: 1000,
    totalRevenueIQD: 100000,
    totlaItemSales: 10,

  },

  {
    storeId: 1,
    userId: 1,
    itemId: 1,
    isStore: false,
    itemName: 'itemName',
    weekViews: 100,
    dayViews: 10,
    lifeTimeViews: 1000,
    totalStars: 4,
    totalReviewers: 10,
    totlaShares: 10,
    totalComments: 19,
    totalRevenueUSD: 1000,
    totalRevenueIQD: 100000,
    totlaItemSales: 10,

  },

  {
    storeId: 1,
    userId: 1,
    itemId: 1,
    isStore: false,
    itemName: 'itemName',
    weekViews: 100,
    dayViews: 10,
    lifeTimeViews: 1000,
    totalStars: 4,
    totalReviewers: 10,
    totlaShares: 10,
    totalComments: 19,
    totalRevenueUSD: 1000,
    totalRevenueIQD: 100000,
    totlaItemSales: 10,
  },

  {
    storeId: 1,
    userId: 1,
    itemId: 1,
    isStore: false,
    itemName: 'itemName',
    weekViews: 100,
    dayViews: 10,
    lifeTimeViews: 1000,
    totalStars: 4,
    totalReviewers: 10,
    totalShares: 10,
    totalComments: 19,
    totalRevenueUSD: 1000,
    totalRevenueIQD: 100000,
    totlaItemSales: 10,

  },

  {
    storeId: 1,
    userId: 1,
    itemId: 1,
    isStore: false,
    itemName: 'itemName',
    weekViews: 100,
    dayViews: 10,
    lifeTimeViews: 1000,
    totalStars: 4,
    totalReviewers: 10,
    totlaShares: 10,
    totalComments: 19,
    totalRevenueUSD: 1000,
    totalRevenueIQD: 100000,
    totlaItemSales: 10,

  },
  {
    storeId: 1,
    userId: 1,
    itemId: 1,
    itemName: 'itemName',
    isStore: false,
    weekViews: 100,
    dayViews: 10,
    lifeTimeViews: 1000,
    totalStars: 4,
    totalReviewers: 10,
    totlaShares: 10,
    totalComments: 19,
    totalRevenueUSD: 1000,
    totalRevenueIQD: 100000,
    totlaItemSales: 10,

  },
];

export default analytics;
